# Generated by Django 3.2.16 on 2022-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_assetgroup_display_amount_in_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_amount_in_base_unit',
            field=models.BooleanField(default=False),
        ),
    ]
