# Generated by Django 3.2.16 on 2023-03-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_assettype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
