# Generated by Django 3.2.16 on 2023-04-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_networth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networth',
            name='baseunit',
        ),
        migrations.AddField(
            model_name='baseunit',
            name='networth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.networth'),
            preserve_default=False,
        ),
    ]
