# Generated by Django 3.2.16 on 2023-08-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='tradetype',
        ),
        migrations.DeleteModel(
            name='TradeAllocation',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeType',
        ),
    ]
