# Generated by Django 3.2.16 on 2023-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_instrument_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
    ]
