# Generated by Django 3.2.16 on 2023-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_instrument_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('IN', 'India')], default='IN', max_length=2),
            preserve_default=False,
        ),
    ]
