# Generated by Django 3.2.16 on 2023-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('IN', 'India'), ('OTH', 'Others')], max_length=4),
        ),
    ]
