# Generated by Django 3.2.16 on 2023-10-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('CN', 'China'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('FR', 'France'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('KR', 'South Korea'), ('TW', 'Taiwan'), ('CH', 'Switzerland'), ('AU', 'Australia'), ('NL', 'Netherlands'), ('IR', 'Iran'), ('ZA', 'South Africa'), ('BR', 'Brazil'), ('SE', 'Sweden'), ('ES', 'Spain')], max_length=4),
        ),
    ]
