# Generated by Django 3.2.16 on 2023-10-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_usernominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernominee',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('U', 'Unsubscribed')], default='A', max_length=20),
        ),
    ]
