# Generated by Django 3.2.16 on 2024-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20240228_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroupbackup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorybackup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrumentbackup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
