# Generated by Django 3.2.16 on 2024-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20240228_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='name',
            field=models.CharField(default='some', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('Not-Started', 'Not-Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], default='Not-Started', max_length=20),
        ),
    ]
