# Generated by Django 3.2.16 on 2024-09-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_pdfdocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
