# Generated by Django 5.1.1 on 2024-10-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_pdfdocument_backend_doc_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='home.pdfdocument')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
