# Generated by Django 5.1.2 on 2024-10-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_pdfdocumentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocumentstatus',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failure', 'Failure')], max_length=50),
        ),
    ]
