# Generated by Django 3.2.16 on 2023-04-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_baseunit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networth',
            old_name='unit',
            new_name='baseunit',
        ),
    ]
