# Generated by Django 3.2.16 on 2023-04-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_networth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='networth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='networth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.networth'),
        ),
    ]
