# Generated by Django 3.2.16 on 2023-04-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230403_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
