# Generated by Django 3.2.16 on 2023-08-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20230831_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='weightage',
            field=models.IntegerField(default=0),
        ),
    ]
