# Generated by Django 3.2.16 on 2023-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_usernominee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], default='F', max_length=20),
        ),
    ]
