# Generated by Django 3.2.16 on 2024-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_backup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroupbackup',
            name='src_asset_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorybackup',
            name='src_category_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentbackup',
            name='src_instrument_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networthbackup',
            name='src_networth_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
