# Generated by Django 3.2.16 on 2024-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20240228_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetgroupbackup',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categorybackup',
            name='networth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instrumentbackup',
            name='asset',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='networthbackup',
            name='user',
            field=models.IntegerField(),
        ),
    ]
