version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pdffusiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s 
      timeout: 5s
      retries: 5
volumes:
  postgres_data: